language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  - CI=true
  script:
    - npm run build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $gitub_token  # Set in the settings page of your repository, as a secure variable
  local_dir: storybook-static  # 我要上传那个文件夹里面的内容
  on:
    branch: master